name: 'yq'
description: 'Run a yq command'
inputs:
  command:
    description: 'yq command to run'
    required: true
runs:
  using: 'docker'
  image: 'mikefarah/yq:4'
  args:
  - sh
  - -c
  - ${{ inputs.command }}