name: update-version

on:
  repository_dispatch:
    types:
    - update-chart

jobs:
  verify-connection:
    runs-on: ubuntu-latest
    steps:
      - name: lima charlie
        id: echo
        run: echo ${{ github.event.client_payload.sha8 }}
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Update docker image tag in target file
        uses: mikefarah/yq@v4.22.1
        with:
          cmd: >
            yq -i '.image.tag = "${{ github.event.client_payload.sha8 }}"
            | .image.tag tag = "!!str"
            | .image.tag style="double"'
            '${{ github.event.client_payload.target_file }}'
      - name: Create Pull Request
        id: createpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update docker image tag
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          labels: automation
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.createpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.createpr.outputs.pull-request-url }}"
