name: update-version

on:
  repository_dispatch:
    types:
    - update-chart

jobs:
  verify-connection:
    runs-on: ubuntu-latest
    steps:
      - name: lima sierra
        id: echo
        run: echo ${{ github.event.client_payload.sha8 }}